// <auto-generated />
using System;
using EventPulse.PaymentService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventPulse.PaymentService.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.1.25081.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventPulse.PaymentService.Models.Payment", entity =>
            {
                entity.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                entity.Property<decimal>("Amount")
                    .HasColumnType("decimal(18,2)");

                entity.Property<Guid>("BookingId")
                    .HasColumnType("uuid");

                entity.Property<string>("BookingReference")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                entity.Property<DateTimeOffset?>("CompletedAt")
                    .HasColumnType("timestamp with time zone");

                entity.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                entity.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                entity.Property<Guid>("CustomerId")
                    .HasColumnType("uuid");

                entity.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                entity.Property<string>("StripePaymentIntentId")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                entity.Property<string>("StripeSessionId")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                entity.HasKey("Id");

                entity.HasIndex("BookingId");

                entity.HasIndex("StripeSessionId");

                entity.ToTable("Payments");
            });
#pragma warning restore 612, 618
        }
    }
}